import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { AiUser } from './entities/ai-user.entity';

@Injectable()
export class AiService {
  constructor(
    private readonly configService: ConfigService,
    @InjectRepository(AiUser)
    private readonly aiUserRepo: Repository<AiUser>,
  ) {}

  async getAiUserWithProfile(id: number) {
    return this.aiUserRepo.findOne({
      where: { id },
      relations: ['aiProfile'],
    });
  }

  async generateText(
    prompt: string,
    type: 'blog' | 'social' | 'ad',
  ): Promise<string> {
    // Mock implementation - replace with OpenAI/Anthropic API call
    return `[IA GENERATED] ${type.toUpperCase()} content for: ${prompt}. This is a high-quality text generated by Hipster AI.`;
  }

  async generateImage(
    prompt: string,
    style: 'realistic' | 'cartoon' | 'sketch',
  ): Promise<string> {
    // Mock implementation - replace with Midjourney/DALL-E API call
    // Returning a placeholder image URL
    return `https://via.placeholder.com/1024x1024.png?text=${encodeURIComponent(prompt)}+(${style})`;
  }

  async generateDocument(
    type: 'legal' | 'business',
    params: any,
  ): Promise<string> {
    // Mock implementation
    return `[IA DOCUMENT] Generated ${type} document with params: ${JSON.stringify(params)}`;
  }

  async applyWatermark(imageUrl: string, isPremium: boolean): Promise<string> {
    if (isPremium) {
      return imageUrl; // No watermark for premium
    }
    // Mock watermark logic
    return `${imageUrl}&watermark=hipster_studio`;
  }
}
